# Generated by Django 5.0.7 on 2024-12-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='user',
            new_name='applicant',
        ),
    ]
